In [3]:
# Q 1

class Employee:
    # DATA MEMBER TO COUNT THE NUMBER OF EMPLOYEES
    empCount = 0

    # CONSTRUCTOR TO INITIALIZE NAME, FAMILY, SALARY, DEPARTMENT
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1    # EMPLOYEE COUNT

    # FUNCTION FOR AVERAGE SALARY OF EMPLOYEE
    def avg_salary(self):
        total_salary = 0
        total_salary += float(self.salary)
        avg = total_salary / Employee.empCount
        print('Average salary of the Employee:', avg)

    # TO DISPLAY DETAILS OF EMPLOYEE
    def display(self):
        print('Employee Name:', self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print("==========")

# INHERITING - EMPLOYEE CLASS
class Fulltime_Employee(Employee):
    def __init__(self, name, family, salary, department, emp_type):
        Employee.__init__(self, name, family, salary, department)
        self.emp_type = emp_type

    #FUNCTION TO DISPLAY EMPLOYEE DETAILS
    def display(self):
        print("Employee Name :", self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print('Type of Employment :', self.emp_type)
        print("==========")


# INSTANCES FOR EMPLOYEE CLASS
emp1 = Employee('Sai Krishna', '4', '125000', 'Cloud Engineer')
# INSTANCE FOR FULL TIME EMPLOYEE
emp2 = Fulltime_Employee('Meenakshi', '3', '110000', 'DevOps Engineer', 'Fulltime')
emp3 = Fulltime_Employee('Srinivas', '4', '85000', 'System Engineer', 'Fulltime')
emp4 = Fulltime_Employee('Aravind', '2', '78000', 'Network Engineer', 'Fulltime')

print("Count of the Employees :", emp1.empCount)
emp1.avg_salary()
emp1.display()
emp2.display()
emp3.display()
emp4.display()

Count of the Employees : 4
Average salary of the Employee: 31250.0
Employee Name: Sai Krishna
Family Members: 4
Employee Annual Salary: 125000
Department: Cloud Engineer
Employee Name : Meenakshi
Family Members: 3
Employee Annual Salary: 110000
Department: DevOps Engineer
Type of Employment : Fulltime
Employee Name : Srinivas
Family Members: 4
Employee Annual Salary: 85000
Department: System Engineer
Type of Employment : Fulltime
Employee Name : Aravind
Family Members: 2
Employee Annual Salary: 78000
Department: Network Engineer
Type of Employment : Fulltime


In [4]:
# Q 2

import numpy as np

# creating array of size 0
random_vector = np.random.uniform(1, 20, 20)
print("Random Vector : \n", random_vector)

# reshape the array to 4 by 5
random_vector = random_vector.reshape(4,5)
print("after reshaping (4 by 5): \n", random_vector)

# replace the max in each row
random_vector[np.arange(len(random_vector)), random_vector.argmax(1)] = 0
print("Replacing the max in each row : \n", random_vector)

Random Vector : 
 [13.53124664  2.80993511  4.00223404 10.4607186   7.97971132  5.46821638
  8.98242681  5.24010318  5.25130758 17.5374968  19.22423966  7.20079143
  5.23673144 11.77874698  3.71563622  9.5957736   3.8471386   7.41228435
 17.84537128 18.06485795]
after reshaping (4 by 5): 
 [[13.53124664  2.80993511  4.00223404 10.4607186   7.97971132]
 [ 5.46821638  8.98242681  5.24010318  5.25130758 17.5374968 ]
 [19.22423966  7.20079143  5.23673144 11.77874698  3.71563622]
 [ 9.5957736   3.8471386   7.41228435 17.84537128 18.06485795]]
Replacing the max in each row : 
 [[ 0.          2.80993511  4.00223404 10.4607186   7.97971132]
 [ 5.46821638  8.98242681  5.24010318  5.25130758  0.        ]
 [ 0.          7.20079143  5.23673144 11.77874698  3.71563622]
 [ 9.5957736   3.8471386   7.41228435 17.84537128  0.        ]]
